services:
  mpp:
    image: "mpp-test-arm"
    restart: unless-stopped
    volumes:
      - ./serial.properties:/opt/mpp/serial.properties
      - ./mqtt.properties:/opt/mpp/mqtt.properties
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    # Java debug only
    #ports:
    #  - 5005:5005